### ISSUE TITLE
.htaccess in 1.7

### ISSUE THREAD

**Issue by kaspar-allenbach** [katrinkerber/statamic-filemanager#2]
Note:

There is a new rule in the .htaccess of statamic 1.7:

```
# This will prevent all .html files from being accessed.
# You may want to remove this line if you want to serve
# static files outside of Statamic
RewriteRule ^(.*)?\.html$ - [F,L]
```

This needs to be disabled. Otherwise filemanager won't work.

**Comment by katrinkerber** [comment]
Please refer to the [instructions](https://github.com/katrinkerber/statamic-filemanager#editing-the-htaccess-file) for this.
