### ISSUE TITLE
running from subdirectory is broken when trying to open the file window from the admin panel

### ISSUE THREAD

**Issue by sixfngers** [katrinkerber/statamic-filemanager#5]
this can be solved by updating the BrowseServer function and adding the site root from the config class. otherwise the _add-ons folder will be attempt to be opened from the root of your server and not your site.

function BrowseServer(obj)
          {
              urlobj = obj;
              OpenServerBrowser(
              '".Config::getSiteRoot()."_add-ons/filemanager/lib/index.html',
              screen.width \* 0.7,
              screen.height \* 0.7 ) ;
          }

I just pulled this down and am only getting started with statamic so I might be missing how to set this properly.
great work though.

**Comment by katrinkerber** [comment]
Well spotted David, thank you.
