### ISSUE TITLE
filemanager.css not loading on Windows IIS server

### ISSUE THREAD

**Issue by addisonhall** [katrinkerber/statamic-filemanager#6]
FYI, I just found where the css is not getting loaded within the admin on IIS. Where it should be this:

`<link href="/_add-ons/filemanager/css/filemanager.css" media="all" type="text/css" rel="stylesheet">`

The admin page is loading this:

`<link href="" media="all" type="text/css" rel="stylesheet">`

I've found this to be the behavior on two different IIS environments.

**Comment by katrinkerber** [comment]
Are the CSS file paths of other add-ons correct? From the Redactor, color, or location add-ons for example?

**Comment by addisonhall** [comment]
Yes, Redactor is working fine -- I haven't tried any others. Right now I'm giving the Epic Editor plugin a whirl to see if I get the same results...

**Comment by addisonhall** [comment]
Ok, same results with Epic Editor -- sorry! I'll move this on over to the Statamic guys.

**Comment by katrinkerber** [comment]
You won't with that add-on , as it doesn't call in its own CSS file.

Do you see these paths in the `<head>` on a publish form page?

![screen shot 2014-08-29 at 17 00 40](https://cloud.githubusercontent.com/assets/818635/4092792/b9d3a946-2f95-11e4-8a0b-3101e23c534f.png)

**Comment by addisonhall** [comment]
Epic Editor does call its own javascript, though, and it's not coming through either.

Yep, my `<head>` looks like that, except for the blank href and src here. (the blank js src is Epic Editor)
![statamic-css](https://cloud.githubusercontent.com/assets/3410344/4092907/e2bca55a-2f96-11e4-8582-5cd95180094c.png)

**Comment by katrinkerber** [comment]
I have absolutely no knowledge of IIS, so can't be of any help there nor do I know whether your issues are related.

If the other add-ons’ paths are working, there should be no reason for the filemanager paths not to work - it's the same code. 

Any console log errors that could point you in the right direction?

**Comment by addisonhall** [comment]
There's only one console error stating that 'EpicEditor is not defined'... I'll move this over to the Google+ Statamic community. Thanks for your time (and the add-on)!

**Comment by katrinkerber** [comment]
OK, good luck! Let us know if you find the reason :)

**Comment by addisonhall** [comment]
Good news:
https://plus.google.com/112082351279804924355/posts/HtUeys6Fmbq

**Comment by katrinkerber** [comment]
Great stuff!
